name: KAI Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest] # macos-latest is for MPS tests
        python-version: [3.11]
        # Future additions for GPU testing:
        # include:
        #   - os: ubuntu-latest
        #     python-version: 3.11
        #     cuda-version: '11.8' # Specify your CUDA version

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Set up CUDA
    #   if: matrix.cuda-version
    #   uses: nvidia-github-actions/setup-cuda@v1
    #   with:
    #     cuda-version: ${{ matrix.cuda-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e . # Install project in editable mode

    - name: Install test dependencies
      run: |
        pip install pytest pytest-asyncio pytest-rerunfailures
        
    - name: Run tests
      run: |
        pytest 